import os
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

from alembic.config import Config
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util import rev_id as _gen_rev_id

SAFE_PREFIXES = (
    "op.add_column(",
    "op.create_table(",
    "op.create_index(",
    "op.create_unique_constraint(",
    "op.create_foreign_key(",
    "op.create_primary_key(",
    "op.create_check_constraint(",
)

DANGEROUS_PREFIXES = (
    "op.drop_column(",
    "op.drop_table(",
    "op.drop_index(",
    "op.drop_constraint(",
    "op.alter_column(",
    "op.rename_table(",
    "op.rename_column(",
)

_REVISION_DIR = Path("migrations/versions")


def _create_empty_revision() -> Optional[str]:
    """Create an empty initial revision file if none exists. Returns revision ID or None."""
    if list(_REVISION_DIR.glob("[!.]*.py")):
        return None

    rev = _gen_rev_id()
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S.%f")
    content = f'''"""initial

Revision ID: {rev}
Revises:
Create Date: {timestamp}
"""
revision = "{rev}"
down_revision = None

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass
'''
    filepath = _REVISION_DIR / f"{rev}_initial.py"
    with open(filepath, "w") as f:
        f.write(content)
    return rev


def _classify_migration(filepath: str) -> tuple[list[str], list[str]]:
    """Parse migration file and classify operations into safe/dangerous."""
    with open(filepath) as f:
        content = f.read()

    start_marker = "# ### commands auto generated by Alembic - please adjust! ###"
    end_marker = "# ### end Alembic commands ###"
    start = content.find(start_marker)
    end = content.find(end_marker)

    if start == -1 or end == -1:
        return [], []

    commands_text = content[start:end]

    safe: list[str] = []
    dangerous: list[str] = []

    for line in commands_text.split("\n"):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        stripped = stripped.rstrip(",")
        stripped = re.sub(r"\s+", " ", stripped)
        for prefix in SAFE_PREFIXES:
            if stripped.startswith(prefix):
                safe.append(stripped)
        for prefix in DANGEROUS_PREFIXES:
            if stripped.startswith(prefix):
                dangerous.append(stripped)

    return safe, dangerous


def run_auto_migration() -> None:
    """
    Run Alembic autogenerate and auto-apply only safe operations.

    Safe: add_column, create_table, create_index, create_*_constraint
    Dangerous (skipped): drop_*, alter_column, rename_*
    """
    cfg = Config("alembic.ini")
    script = ScriptDirectory.from_config(cfg)

    # ---- Step 1: Apply any pending (unapplied) migrations ----
    try:
        command.upgrade(cfg, "head")
    except Exception:
        pass

    # ---- Step 2: Get current head before autogenerate ----
    old_head = script.get_current_head()

    # ---- Step 3: Generate autogenerate revision ----
    try:
        command.revision(cfg, autogenerate=True, message="auto_migration")
    except Exception:
        return  # no new changes detected

    # ---- Step 4: Find the new migration file by its revision ID ----
    script = ScriptDirectory.from_config(cfg)
    new_head = script.get_current_head()
    if new_head == old_head or new_head is None:
        return

    rev = script.get_revision(new_head)
    if rev is None or rev.module is None or not hasattr(rev.module, "__file__"):
        return

    rev_file: str | None = rev.module.__file__
    if rev_file is None:
        return

    # ---- Step 5: Classify operations ----
    safe_ops, dangerous_ops = _classify_migration(rev_file)

    if dangerous_ops:
        print(
            f"[!] Alembic: DANGEROUS operations in migration — "
            f"manual review required"
        )
        for op in dangerous_ops:
            print(f"      {op}")
        return

    if safe_ops:
        print(f"[+] Alembic: {len(safe_ops)} safe operation(s) — auto-applying")
        try:
            command.upgrade(cfg, "head")
            print("[+] Alembic: applied successfully")
        except Exception as e:
            print(f"[!] Alembic: upgrade failed — {e}")
    else:
        os.remove(rev_file)
